/* Flyway Migration V10: Refactor Attribute Schema (Full Migration)
   Obsługuje dane z V3 i V7, konwertując je do nowej struktury.
*/

-- ==========================================
-- 1. Tworzenie tabeli słownikowej 'attributes'
-- ==========================================
CREATE TABLE IF NOT EXISTS attributes (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(100) NOT NULL,
                                          type VARCHAR(50) NOT NULL,
                                          created_at TIMESTAMP DEFAULT NOW() NOT NULL,
                                          updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
                                          deleted_at TIMESTAMP,
                                          is_active BOOLEAN DEFAULT TRUE NOT NULL,
                                          CONSTRAINT uc_attributes_name_type UNIQUE (name, type)
);

-- ==========================================
-- 2. Migracja definicji (naprawa danych z V3)
-- ==========================================
-- Kopiujemy unikalne pary nazwa/typ z category_attributes do nowej tabeli
INSERT INTO attributes (name, type, created_at, updated_at, is_active)
SELECT DISTINCT name, type, NOW(), NOW(), true
FROM category_attributes
WHERE name IS NOT NULL AND type IS NOT NULL
ON CONFLICT (name, type) DO NOTHING;

-- ==========================================
-- 3. Przebudowa tabeli 'category_attributes'
-- ==========================================
ALTER TABLE category_attributes ADD COLUMN IF NOT EXISTS attribute_id BIGINT;

-- Linkujemy istniejące rekordy do nowej tabeli attributes
UPDATE category_attributes ca
SET attribute_id = a.id
    FROM attributes a
WHERE ca.name = a.name AND ca.type = a.type;

-- Usuwamy śmieci (rekordy których nie udało się zlinkować)
DELETE FROM category_attributes WHERE attribute_id IS NULL;
ALTER TABLE category_attributes ALTER COLUMN attribute_id SET NOT NULL;

-- Usuwamy stare kolumny (name, type) z tej tabeli
ALTER TABLE category_attributes
    DROP COLUMN IF EXISTS name,
DROP COLUMN IF EXISTS type;

-- Dodajemy klucz obcy
ALTER TABLE category_attributes
    ADD CONSTRAINT fk_category_attributes_attribute
        FOREIGN KEY (attribute_id) REFERENCES attributes (id);

-- Dodajemy constraint unikalności (kategoria może mieć dany atrybut tylko raz)
-- Najpierw usuwamy stary constraint jeśli istnieje (z V2)
ALTER TABLE category_attributes DROP CONSTRAINT IF EXISTS category_attributes_category_id_name_key;
ALTER TABLE category_attributes ADD CONSTRAINT uc_category_attribute_link UNIQUE (category_id, attribute_id);


-- ==========================================
-- 4. Przebudowa tabeli 'product_attribute_values' (Naprawa danych z V7)
-- ==========================================

-- A. Dodajemy nową kolumnę
ALTER TABLE product_attribute_values ADD COLUMN IF NOT EXISTS attribute_id BIGINT;

-- B. DATA MIGRATION: Przeliczamy ID.
UPDATE product_attribute_values pav
SET attribute_id = ca.attribute_id
FROM category_attributes ca
WHERE pav.category_attribute_id = ca.id;

-- C. Jeśli jakieś wartości nie mają odpowiednika, usuwamy je
DELETE FROM product_attribute_values WHERE attribute_id IS NULL;
ALTER TABLE product_attribute_values ALTER COLUMN attribute_id SET NOT NULL;

-- D. Usuwamy starą kolumnę category_attribute_id
ALTER TABLE product_attribute_values DROP CONSTRAINT IF EXISTS product_attribute_values_product_id_category_attribute_id_key;
ALTER TABLE product_attribute_values DROP CONSTRAINT IF EXISTS product_attribute_values_category_attribute_id_fkey;
ALTER TABLE product_attribute_values DROP COLUMN category_attribute_id;

-- E. Dodajemy nowy klucz obcy
ALTER TABLE product_attribute_values
    ADD CONSTRAINT fk_product_attr_val_attribute
        FOREIGN KEY (attribute_id) REFERENCES attributes (id);

-- E2. [FIX] DEDUPLIKACJA: Usuwamy identyczne wiersze przed nałożeniem constrainta
-- Zostawiamy ten z najniższym ID, usuwamy resztę
DELETE FROM product_attribute_values a
    USING product_attribute_values b
WHERE a.id > b.id
  AND a.product_id = b.product_id
  AND a.attribute_id = b.attribute_id
  AND a.value = b.value;

-- F. Dodajemy constraint unikalności (Produkt + Atrybut + Wartość)
ALTER TABLE product_attribute_values
    ADD CONSTRAINT uc_product_attribute_val_unique_content UNIQUE (product_id, attribute_id, value);
-- 5. Indeksy
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_prod_attr_val_attr_id ON product_attribute_values(attribute_id);