
CREATE TABLE IF NOT EXISTS attributes (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(100) NOT NULL,
                                          type VARCHAR(50) NOT NULL,
                                          created_at TIMESTAMP DEFAULT NOW() NOT NULL,
                                          updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
                                          deleted_at TIMESTAMP,
                                          is_active BOOLEAN DEFAULT TRUE NOT NULL,
                                          CONSTRAINT uc_attributes_name_type UNIQUE (name, type)
);


INSERT INTO attributes (name, type, created_at, updated_at, is_active)
SELECT DISTINCT name, type, NOW(), NOW(), true
FROM category_attributes
WHERE name IS NOT NULL AND type IS NOT NULL
ON CONFLICT (name, type) DO NOTHING;


ALTER TABLE category_attributes ADD COLUMN IF NOT EXISTS attribute_id BIGINT;


UPDATE category_attributes ca
SET attribute_id = a.id
    FROM attributes a
WHERE ca.name = a.name AND ca.type = a.type;


DELETE FROM category_attributes WHERE attribute_id IS NULL;
ALTER TABLE category_attributes ALTER COLUMN attribute_id SET NOT NULL;


ALTER TABLE category_attributes
    DROP COLUMN IF EXISTS name,
DROP COLUMN IF EXISTS type;


ALTER TABLE category_attributes
    ADD CONSTRAINT fk_category_attributes_attribute
        FOREIGN KEY (attribute_id) REFERENCES attributes (id);

ALTER TABLE category_attributes DROP CONSTRAINT IF EXISTS category_attributes_category_id_name_key;
ALTER TABLE category_attributes ADD CONSTRAINT uc_category_attribute_link UNIQUE (category_id, attribute_id);

ALTER TABLE product_attribute_values ADD COLUMN IF NOT EXISTS attribute_id BIGINT;


UPDATE product_attribute_values pav
SET attribute_id = ca.attribute_id
FROM category_attributes ca
WHERE pav.category_attribute_id = ca.id;

DELETE FROM product_attribute_values WHERE attribute_id IS NULL;
ALTER TABLE product_attribute_values ALTER COLUMN attribute_id SET NOT NULL;


ALTER TABLE product_attribute_values DROP CONSTRAINT IF EXISTS product_attribute_values_product_id_category_attribute_id_key;
ALTER TABLE product_attribute_values DROP CONSTRAINT IF EXISTS product_attribute_values_category_attribute_id_fkey;
ALTER TABLE product_attribute_values DROP COLUMN category_attribute_id;


ALTER TABLE product_attribute_values
    ADD CONSTRAINT fk_product_attr_val_attribute
        FOREIGN KEY (attribute_id) REFERENCES attributes (id);


DELETE FROM product_attribute_values a
    USING product_attribute_values b
WHERE a.id > b.id
  AND a.product_id = b.product_id
  AND a.attribute_id = b.attribute_id
  AND a.value = b.value;


ALTER TABLE product_attribute_values
    ADD CONSTRAINT uc_product_attribute_val_unique_content UNIQUE (product_id, attribute_id, value);

CREATE INDEX IF NOT EXISTS idx_prod_attr_val_attr_id ON product_attribute_values(attribute_id);